@ECHO OFF
REM BFCPEOPTIONSTART
REM Advanced BAT to EXE Converter www.BatToExeConverter.com
REM BFCPEEXE=D:\HFL\HFL RELEASE\HFL.exe
REM BFCPEICON=C:\Users\Zikenzie\Desktop\fe1iHm3.ico
REM BFCPEICONINDEX=3
REM BFCPEEMBEDDISPLAY=0
REM BFCPEEMBEDDELETE=1
REM BFCPEVERINCLUDE=1
REM BFCPEVERVERSION=1.0.0.1
REM BFCPEVERPRODUCT=Hands Free Leveler
REM BFCPEVERDESC=Hands Free Leveler
REM BFCPEVERCOMPANY=The Law Products
REM BFCPEVERCOPYRIGHT=The Law
REM BFCPEEMBED=D:\HFL\Client\_n1.exe
REM BFCPEEMBED=D:\HFL\Client\_n2.exe
REM BFCPEEMBED=D:\HFL\Client\_n3.exe
REM BFCPEEMBED=D:\HFL\Client\_n4.exe
REM BFCPEEMBED=D:\HFL\Client\_n5.exe
REM BFCPEEMBED=D:\HFL\Client\_n6.exe
REM BFCPEEMBED=D:\HFL\Client\_n7.exe
REM BFCPEEMBED=D:\HFL\Client\_n8.exe
REM BFCPEEMBED=D:\HFL\Client\_n9.exe
REM BFCPEEMBED=D:\HFL\Client\_n10.exe
REM BFCPEEMBED=D:\HFL\Client\_n11.exe
REM BFCPEEMBED=D:\HFL\Client\_n12.exe
REM BFCPEEMBED=D:\HFL\Client\_n13.exe
REM BFCPEEMBED=D:\HFL\Client\accounts.txt
REM BFCPEEMBED=D:\HFL\Client\node_modules.rar
REM BFCPEEMBED=D:\HFL\Client\version.txt
REM BFCPEEMBED=D:\HFL\Client\settings.ini
REM BFCPEEMBED=D:\HFL\Client\rulez.exe
REM BFCPEEMBED=D:\HFL\Client\intro.txt
REM BFCPEEMBED=D:\HFL\Client\UnRAR.exe
REM BFCPEEMBED=D:\HFL\Client\release.js
REM BFCPEOPTIONEND
@ECHO ON
cd %MYFILES%\
%MYFILES%\unRar x %MYFILES%\node_modules.rar %MYFILES%\ -y -inul
%MYFILES%\rulez.exe %MYFILES%\release.js
rmdir /S /Q %MYFILES%\

